name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - 
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://hugeota.d.miui.com/20.5.21/miui_HMNote5_20.5.21_2f072b7ae5_9.0.zip
  ROM_NAME: MIUI
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Cleaning up
         run: |
           docker rmi `docker images -q`

       - name: Cloning ErfanGSIs tools
         run: |
            git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
            sudo chmod -R 777 ErfanGSIs
             
       - name: Setting up Porting Environment
         run: |
           cd ErfanGSIs
           sudo apt update
           sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME -ab
       
       - name: Compassing GSI
         run: |
              mkdir releasing
              sudo mv /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/* releasing/
              echo "Deleting ErfanGSIs tools"
              sudo rm -rf ErfanGSIs 
              echo "Compassing GSI with britli"
              sudo brotli -q 6 -j -o GSI-AB.br releasing/MIUI-AB-10-*-ErfanGSI.img
              sudo brotli -q 6 -j -o GSI-A.br releasing/MIUI-Aonly-10-*-ErfanGSI.img
              echo "Compassing GSI with 7zip"
              7z a -r GSI-AB.7z GSI-AB.br
              sudo rm GSI-AB.br
              7z a -r GSI-A.7z GSI-A.br
              sudo rm GSI-A.br
       
       - name: Upload GSI to Airportal
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer cow GSI-AB.7z
              ./transfer cow GSI-A.7z
